dist: trusty
sudo: required
before_install:
  - echo $(cat /proc/cpuinfo)
  - echo $(free)
language: java
jdk:
  - oraclejdk8
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
      - ant-optional
