version: 2
jobs:
  build:
    working_directory: ~/cassandra
    parallelism: 4
    machine:
      java:
        version: 'oraclejdk8'
    steps:
      - run:
          name: Install Dependencies
          command: |
            npm install -g junit-merge
            sudo pip install virtualenv
            sudo ifconfig -a
            sudo ifconfig lo:1 127.0.0.2 up
            sudo ifconfig lo:2 127.0.0.3 up
            sudo ifconfig lo:3 127.0.0.4 up
            sudo ifconfig lo:4 127.0.0.5 up
            sudo ifconfig lo:4 127.0.0.6 up
            sudo ifconfig lo:4 127.0.0.7 up
            sudo ifconfig lo:4 127.0.0.8 up
            sudo ifconfig lo:4 127.0.0.9 up
            echo git clone --single-branch --depth 1 https://github.com/riptano/cassandra-dtest ~/cassandra-dtest
            git clone --single-branch --depth 1 https://github.com/riptano/cassandra-dtest ~/cassandra-dtest
            echo git clone --single-branch --depth 1 --branch $CIRCLE_BRANCH git://github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME.git ~/cassandra
            git clone --single-branch --depth 1 --branch $CIRCLE_BRANCH git://github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME.git ~/cassandra 
            virtualenv --python=python2 --no-site-packages venv
            source venv/bin/activate
#            pip install -r ~/cassandra-dtest/requirements.txt
#            pip freeze
#      - run:
#          name: Build Cassandra
#          command: cd ~/cassandra && ant build
      - run:
          name: Unit Tests
          command: |
            echo `circleci tests glob "$HOME/cassandra/test/unit/**" "$HOME/cassandra-dtest/**/*.py" | grep -v upgrade_tests |  circleci tests split --split-by=timings --timings-type=filename` > /tmp/tests.txt
            cat /tmp/tests.txt
            echo "***python tests***"
            echo `cat /tmp/tests.txt | grep "*\.py"` > /tmp/python_tests.txt
            cat /tmp/python_tests.txt
            echo "***java tests***"
            echo `cat /tmp/tests.txt | grep "*\.java"` > /tmp/java_tests.txt
            cat /tmp/java_tests.txt
